# declare general sentence structure for reference
sentence structure: [A-S-V-O, S-O (0.1)]

# declare usable words, don't need to be included in sentence structure
# extends replaces other settings granuarly
words:
  articles:
    identification: A
    limit: 7
    extends:
      char limit:
        min: 2
        max: 4
      rules:
        VOWEL: ['g (0.9)', 'VOWEL']
    # a: [sd (0.7)]
  subject: S
  verb: V
  object: O

# used alphabet, combinations possible
alphabet: [GERMAN, ENGLISH (0.2)]

# char limiter
char limit:
  min: 1
  max: 10

# used vowels - if you really want to be special use 0 as min and max
vowels:
  charlist:
    - INHERIT
    - a (0.3)
  min: 1
  max: 4

# additional rules o follows with s possibility of 0.5
# the use of VOWEL and CONSONANT is only allowed in the latin alphabet or if declared in the vowels section
rules:
  o: [s (0.5)]
  a: [d (0.2)]
  VOWEL: [CONSONANT (0.5), CONSONANTCONSONANT (0.3), CONSONANTCONSONANTCONSONANT (0.2)]
  VOWELVOWEL: [CONSONANTVOWELCONSONANT (0.6)]
